### ISSUE TITLE
[BUG] dir_names + files combo ends up in error

### ISSUE THREAD

**Issue by jkremser** [tj-actions/changed-files#757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When using dir_names: true and files with globs, it ends up with pipe error

### To Reproduce

When calling the action like this:

```yaml
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          dir_names: "true"
          files: |
            **/values.json
            **/values.schema.json
```
(full workflow https://github.com/jkremser/log2rbac-operator/actions/runs/3393837005/workflow)

I got following error:

```bash
Run tj-actions/changed-files@v34
Run # "Calculating the previous and current SHA..."
changed-files-diff-sha
Run tj-actions/glob@v15
/usr/bin/git rev-parse --show-toplevel
/home/runner/work/log2rbac-operator/log2rbac-operator
/usr/bin/git diff --diff-filter=D --name-only 60ae0af0ea0ee489[39](https://github.com/jkremser/log2rbac-operator/actions/runs/3393806933/jobs/5641569331#step:5:41)13e8a498b53ce1497abd48 6628f93e06c0e58948add09bba03513dd0566780
Run bash $GITHUB_ACTION_PATH/get-changed-paths.sh
changed-files
  Resolving repository path: /home/runner/work/log2rbac-operator/log2rbac-operator/.
  Retrieving changes between 60ae0af0ea0ee4893913e8a498b53ce1497abd48 (master) → 6628f93e06c0e58948add09bba03513dd0566780 (helm-json-schema)
  grep: : No such file or directory
  fatal: 60ae0af0ea0ee4893913e8a498b53ce1497abd48...6628f93e06c0e58948add09bba03513dd0566780: no merge base
  /home/runner/work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 59: echo: write error: Broken pipe
  Error: Process completed with exit code 1.
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

list of directories where those files specified in `files` are

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @jkremser can you verify that this has been resolved. Thanks

**Comment by SiddhantSadangi** [comment]
I don't see any error, but using file filters still breaks `dir_names`

Without filters
```
      - name: Get changed directories
        id: changed-dirs
        uses: tj-actions/changed-files@v34
        with:
          dir_names: "true"
          json: true
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-dirs.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
```
This lists changes.
Link to run: https://github.com/neptune-ai/examples/actions/runs/3407737702/jobs/5667669387

With filters
```
      - name: Get changed directories
        id: changed-dirs
        uses: tj-actions/changed-files@v34
        with:
          dir_names: "true"
          json: true
          files: |
            **/scripts/*
          files_ignore: |
            **/neptune-docker/*
            **/kedro/*
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-dirs.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
```
This doesn't return any changes.
Link to run: https://github.com/neptune-ai/examples/actions/runs/3407713523/jobs/5667617759

**Comment by jackton1** [comment]
@SiddhantSadangi I'll recommend swapping `*` for `**` I.e `**/scripts/*` to **/scripts/**``

**Comment by jbritt1** [comment]
The original issue still exists. The second user changed the issue where they were dir names and filtering other dirs. Combining dir names and files however still produces an error or an empty array.

**Comment by jbritt1** [comment]
@jackton1, any thoughts?

**Comment by jbritt1** [comment]
Here is an example of the broken pipe from the original issue as well: 

![image](https://user-images.githubusercontent.com/56260532/208142092-fe6863b0-96db-4969-af5d-a992f742cc70.png)
